name: Build and test

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Qt
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y qt6-base-dev

      - name: Build application
        run: qmake6 TicTacToe.pro && make -j2

      - name: Build and run rule tests
        working-directory: tests
        run: qmake6 tictactoe_test.pro && make -j2 && ./tictactoe_test
